---
sidebar: sidebar 
permalink: reference-limitations-aws.html 
keywords: limitations, aws, amazon web services, flashe cache, alarms, cloudwatch, giveback, govcloud, c2s 
summary: Essas limitações conhecidas são específicas do Cloud Volumes ONTAP no Amazon Web Services. 
---
= Limitações conhecidas na AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
As limitações conhecidas a seguir são específicas do Cloud Volumes ONTAP no Amazon Web Services. Certifique-se de também rever link:reference-limitations.html["Limitações em todos os provedores de nuvem"].



== Pares DE HA não são compatíveis com AWS Outposts

Os sistemas de nó único são compatíveis com o AWS Outposts, mas os pares de HA não são suportados no momento.



== Limitações do Flash Cache

Os tipos de instância C5D e R5D incluem armazenamento NVMe local, que o Cloud Volumes ONTAP usa como _Flash Cache_. Observe as seguintes limitações:

* A compactação deve ser desativada em todos os volumes para aproveitar as melhorias de desempenho do Flash Cache.
+
Não é possível escolher a eficiência de storage ao criar um volume no Cloud Manager ou criar um volume e, em seguida http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["Desative a compressão de dados usando a CLI"^], .

* O reaquecimento do cache após uma reinicialização não é suportado com o Cloud Volumes ONTAP.




== Alarmes falsos relatados pelo Amazon CloudWatch

O Cloud Volumes ONTAP não libera CPUs quando ocioso, https://aws.amazon.com/cloudwatch/["Amazon CloudWatch"^] então pode relatar um aviso de CPU alto para a instância EC2 porque ele vê 100% de uso. Pode ignorar este alarme. O comando ONTAP statistics exibe o verdadeiro uso das CPUs.



== Os pares de HA do Cloud Volumes ONTAP não são compatíveis com storage imediato para giveback

Depois que um nó é reiniciado, o parceiro deve sincronizar os dados antes que ele possa retornar o armazenamento. O tempo necessário para sincronizar os dados depende da quantidade de dados gravados pelos clientes enquanto o nó estava inativo e da velocidade de gravação de dados durante o tempo de giveback.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha.html["Saiba como o storage funciona em um par de HA do Cloud Volumes ONTAP executado na AWS"^].



== Limitações no ambiente AWS C2S

Ver limitações nos documentos do Cloud Manager: https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-getting-started-aws-c2s.html["Comece a usar o ambiente AWS C2S"^]
