---
sidebar: sidebar 
permalink: reference-limits-aws.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, ebs 
summary: O Cloud Volumes ONTAP tem limites de configuração de storage na AWS para fornecer operações confiáveis. Para obter o melhor desempenho, não configure o sistema com os valores máximos. 
---
= Limites de armazenamento na AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O Cloud Volumes ONTAP tem limites de configuração de storage para fornecer operações confiáveis. Para obter o melhor desempenho, não configure o sistema com os valores máximos.



== Capacidade máxima do sistema por licença

A capacidade máxima do sistema para um sistema Cloud Volumes ONTAP é determinada pela sua licença. A capacidade máxima do sistema inclui storage baseado em disco e storage de objetos usado para categorização de dados. O NetApp não suporta exceder esse limite.

Para algumas configurações de HA, os limites de disco impedem que você alcance o limite de capacidade usando discos somente. Nesses casos, você pode alcançar o limite de capacidade em https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["disposição em camadas dos dados inativos no storage de objetos"^]. Consulte os limites de capacidade e disco abaixo para obter mais detalhes.

[cols="25,75"]
|===
| Licença | Capacidade máxima do sistema (discos e armazenamento de objetos) 


| Freemium | 500 GiB 


| PAYGO Explore | 2 TIB (disposição de dados em categorias não é compatível com o Explore) 


| Padrão PAYGO | 10 TIB 


| PAYGO Premium | 368 TIB 


| Licença baseada em nó | 2 PIB (requer várias licenças) 


| Licença baseada em capacidade | 2 PIB 
|===
.No caso de HA, o limite de capacidade da licença por nó ou para todo o par de HA?
O limite de capacidade aplica-se a todo o par de HA. Não é por nó. Por exemplo, se você usar a licença Premium, poderá ter até 368 TIB de capacidade entre os dois nós.

.Para um sistema de HA na AWS, os dados espelhados contam com limite de capacidade?
Não, não. Os dados em um par de HA da AWS são espelhados de forma síncrona entre os nós para que os dados estejam disponíveis em caso de falha. Por exemplo, se você comprar um disco TIB de 8 TB no nó A, o Cloud Manager também aloca um disco TIB de 8 TB no nó B usado para dados espelhados. Embora 16 TIB de capacidade tenha sido provisionado, apenas 8 TIB conta contra o limite de licença.



== Limites de disco e disposição em camadas por instância do EC2

O Cloud Volumes ONTAP usa volumes EBS como discos, com um tamanho máximo de disco de 16 TIB. As seções abaixo mostram os limites de disco e disposição em categorias por tipo de instância EC2 porque muitos tipos de instância EC2 têm limites de disco diferentes. Os limites de disco também são diferentes entre sistemas de nó único e pares de HA.

Os limites de disco abaixo são específicos para discos que contêm dados de usuário. Os limites não incluem o disco de inicialização e o disco raiz.

* Você pode comprar várias licenças baseadas em nós para um sistema de nó único ou par de HA da Cloud Volumes ONTAP BYOL para alocar mais de 368 TIB de capacidade, até o limite máximo de capacidade do sistema testado e suportado de 2 PIB. Esteja ciente de que os limites de disco podem impedir que você alcance o limite de capacidade usando discos sozinhos. Você pode ir além do limite de disco pelo https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["disposição em camadas dos dados inativos no storage de objetos"^]. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html["Saiba como adicionar licenças de sistema adicionais ao Cloud Volumes ONTAP"^]. Embora o Cloud Volumes ONTAP suporte até a capacidade máxima do sistema testada e suportada de 2 PIB, cruzar o limite de 2 PIB resulta em uma configuração de sistema não suportada.
+
** As regiões de nuvem secreta da AWS e da nuvem secreta principal suportam a compra de várias licenças baseadas em nós a partir do Cloud Volumes ONTAP 9.12.1.






=== Nó único com licença Premium

[cols="18,18,32,32"]
|===
| Família da instância | Máximo de discos por nó | Capacidade máxima do sistema somente com discos | Capacidade máxima do sistema com discos e categorização de dados 


| instâncias c5, m5 e r5 | 22 | 352 TIB | 368 TIB 


| instâncias c4, m4 e r4 | 34 | 368 TIB | 368 TIB 
|===


=== Nó único com licenciamento baseado em nó

[cols="18,18,16,16,16,16"]
|===
| Família da instância | Máximo de discos por nó 2+| Capacidade máxima do sistema com uma licença 2+| Capacidade máxima do sistema com várias licenças 


2+|  | *Discos sozinhos* | *Discos e categorização de dados* | *Discos sozinhos* | *Discos e categorização de dados* 


| instâncias c5, m5 e r5 | 22 | 352 TIB | 368 TIB | 352 TIB | 2 PIB 


| instâncias c4, m4 e r4 | 34 | 368 TIB | 368 TIB | 544 TIB | 368 TIB x cada licença 
|===


=== Nó único com licenciamento baseado em capacidade

[cols="18,18,32,32"]
|===
| Família da instância | Máximo de discos por nó | Capacidade máxima do sistema somente com discos | Capacidade máxima do sistema com discos e categorização de dados 


| instâncias c5, m5 e r5 | 22 | 352 TIB | 2 PIB 


| instâncias c4, m4 e r4 | 34 | 544 TIB | 2 PIB 
|===


=== PARES DE HA com uma licença Premium

[cols="18,18,32,32"]
|===
| Família da instância | Máximo de discos por nó | Capacidade máxima do sistema somente com discos | Capacidade máxima do sistema com discos e categorização de dados 


| instâncias c5, m5 e r5 | 19 | 304 TIB | 368 TIB 


| instâncias c4, m4 e r4 | 31 | 368 TIB | 368 TIB 
|===


=== Pares DE HA com licenciamento baseado em nó

[cols="18,18,16,16,16,16"]
|===
| Família da instância | Máximo de discos por nó 2+| Capacidade máxima do sistema com uma licença 2+| Capacidade máxima do sistema com várias licenças 


2+|  | *Discos sozinhos* | *Discos e categorização de dados* | *Discos sozinhos* | *Discos e categorização de dados* 


| instâncias c5, m5 e r5 | 19 | 304 TIB | 368 TIB | 304 TIB | 2 PIB 


| instâncias c4, m4 e r4 | 31 | 368 TIB | 368 TIB | 496 TIB | 368 TIB x cada licença 
|===


=== Pares DE HA com licenciamento baseado em capacidade

[cols="18,18,32,32"]
|===
| Família da instância | Máximo de discos por nó | Capacidade máxima do sistema somente com discos | Capacidade máxima do sistema com discos e categorização de dados 


| instâncias c5, m5 e r5 | 19 | 304 TIB | 2 PIB 


| instâncias c4, m4 e r4 | 31 | 496 TIB | 2 PIB 
|===


== Limites agregados

O Cloud Volumes ONTAP usa volumes AWS como discos e os agrupa em _agregados_. Agregados fornecem storage para volumes.

[cols="2*"]
|===
| Parâmetro | Limite 


| Número máximo de agregados | Nó único: O mesmo que os pares HA de limite de disco: 18 em um nó 1 


| Tamanho máximo de agregado | 96 TIB de capacidade bruta 2 


| Discos por agregado | 1-6 3 


| Número máximo de grupos RAID por agregado | 1 
|===
Notas:

. Não é possível criar agregados 19 em ambos os nós em um par de HA, pois isso excederia o limite do disco de dados.
. O limite de capacidade agregada é baseado nos discos que compõem o agregado. O limite não inclui o storage de objetos usado para categorização de dados.
. Todos os discos em um agregado devem ter o mesmo tamanho.




== Limites lógicos de armazenamento

[cols="22,22,56"]
|===
| Storage lógico | Parâmetro | Limite 


| *Storage VMs (SVMs)* | Número máximo de Cloud Volumes ONTAP (par de HA ou nó único)  a| 
*Instâncias C5, M5 e R5 com BYOL* o seguinte número de VMs de armazenamento é compatível com os tipos de instância C5, M5 e R5 quando você traz sua própria licença (BYOL):

* 12 VMs de storage com sistemas de nó único
* 8 VMs de storage com pares de HA



NOTE: Uma VM de storage abrange todo o sistema Cloud Volumes ONTAP (par de HA ou nó único)

Uma licença complementar é necessária para cada SVM adicional de fornecimento de dados além da primeira VM de storage fornecida com o Cloud Volumes ONTAP por padrão. Entre em Contato com sua equipe de conta para obter uma licença complementar da SVM.

As VMs de storage configuradas para recuperação de desastres (DR) não exigem uma licença complementar (elas são gratuitas), mas contam com o limite de VM de storage. 1,2

*Todas as outras configurações* são suportadas uma VM de armazenamento de dados e uma VM de armazenamento de destino usada para recuperação de desastres. 2

Uma VM de storage abrange todo o sistema Cloud Volumes ONTAP (par de HA ou nó único).



.2+| *Ficheiros* | Tamanho máximo | 16 TIB 


| Máximo por volume | Depende do tamanho do volume, até 2 bilhões 


| *Volumes FlexClone* | Profundidade do clone hierárquico 3 | 499 


.3+| *Volumes FlexVol* | Máximo por nó | 500 


| Tamanho mínimo | 20 MB 


| Tamanho máximo | 100 TIB 


| *Qtrees* | Máximo por FlexVol volume | 4.995 


| *Cópias Snapshot* | Máximo por FlexVol volume | 1.023 
|===
Notas:

. Por exemplo, se você tiver 8 VMs de storage de fornecimento de dados em um par de HA, atingiu o limite e não poderá criar VMs de storage adicionais. O mesmo acontece com outro par de HA que tem 8 VMs de storage configuradas para recuperação de desastres - você atingiu o limite e não pode criar VMs de storage adicionais.
. Você pode ativar uma VM de storage de destino para acesso aos dados se houver uma interrupção na VM de storage de origem. O Cloud Manager não oferece suporte de configuração ou orquestração para recuperação de desastres de VM de storage. Você deve usar o System Manager ou a CLI.
+
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856["Guia expresso de preparação para recuperação de desastres da SVM"^]
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857["Guia do SVM Disaster Recovery Express"^]


. Profundidade de clone hierárquica é a profundidade máxima de uma hierarquia aninhada de volumes FlexClone que pode ser criada a partir de um único FlexVol volume.




== Limites de armazenamento iSCSI

[cols="3*"]
|===
| Armazenamento iSCSI | Parâmetro | Limite 


.4+| *LUNs* | Máximo por nó | 1.024 


| Número máximo de mapas LUN | 1.024 


| Tamanho máximo | 16 TIB 


| Máximo por volume | 512 


| *grupos* | Máximo por nó | 256 


.2+| *Iniciadores* | Máximo por nó | 512 


| Máximo por grupo | 128 


| * Sessões iSCSI* | Máximo por nó | 1.024 


.2+| *LIFs* | Máximo por porta | 32 


| Máximo por portset | 32 


| *Portsets* | Máximo por nó | 256 
|===