---
sidebar: sidebar 
permalink: reference-limits-gcp.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM 
summary: O Cloud Volumes ONTAP tem limites de configuração de storage no Google Cloud para fornecer operações confiáveis. Para obter o melhor desempenho, não configure o sistema com os valores máximos. 
---
= Limites de armazenamento no Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O Cloud Volumes ONTAP tem limites de configuração de storage para fornecer operações confiáveis. Para obter o melhor desempenho, não configure o sistema com os valores máximos.



== Capacidade máxima do sistema por licença

A capacidade máxima do sistema para um sistema Cloud Volumes ONTAP é determinada pela sua licença. A capacidade máxima do sistema inclui storage baseado em disco e storage de objetos usado para categorização de dados. O NetApp não suporta exceder esse limite.

Para algumas configurações, os limites de disco impedem que você alcance o limite de capacidade usando discos sozinhos. Você pode alcançar o limite de capacidade por https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["disposição em camadas dos dados inativos no storage de objetos"^]. Consulte os limites de disco abaixo para obter mais detalhes.

[cols="25,75"]
|===
| Licença | Capacidade máxima do sistema (discos e armazenamento de objetos) 


| Freemium | 500 GB 


| PAYGO Explore | 2 TB (a disposição em camadas de dados não é compatível com o Explore) 


| Padrão PAYGO | 10 TB 


| PAYGO Premium | 368 TB 


| Licença baseada em nó | 2 PIB (requer várias licenças) 


| Licença baseada em capacidade | 2 PIB 
|===


== Limites de disco e disposição em camadas

A tabela abaixo mostra a capacidade máxima do sistema com discos somente e com a disposição em camadas de discos e dados inativos no storage de objetos. Os limites de disco são específicos para discos que contêm dados de usuário. Os limites não incluem o disco de inicialização e o disco raiz.

[cols="60,40"]
|===
| Parâmetro | Limite 


| Máximo de discos por sistema | 124 


| Tamanho máximo do disco | 16 TB 


| Capacidade máxima do sistema somente com discos | 256 TB 


| Capacidade máxima do sistema com discos e categorização de dados inativos em um bucket do Google Cloud Storage | Depende da licença. Consulte a tabela acima. 
|===


== Limites agregados

O Cloud Volumes ONTAP agrupa os discos do Google Cloud em _agregados_. Agregados fornecem storage para volumes.

[cols="2*"]
|===
| Parâmetro | Limite 


| Número máximo de agregados de dados | 99 1 


| Tamanho máximo de agregado | 96 TB de capacidade bruta 2 


| Discos por agregado | 1-6 3 


| Número máximo de grupos RAID por agregado | 1 
|===
Notas:

. O número máximo de agregados de dados não inclui o agregado raiz.
. O limite de capacidade agregada é baseado nos discos que compõem o agregado. O limite não inclui o storage de objetos usado para categorização de dados.
. Todos os discos em um agregado devem ter o mesmo tamanho.




== Limites lógicos de armazenamento

[cols="22,22,56"]
|===
| Storage lógico | Parâmetro | Limite 


| *Storage Virtual Machines (SVMs)* | Número máximo para Cloud Volumes ONTAP | Um SVM de fornecimento de dados e um SVM de destino usado na recuperação de desastres. Você pode ativar o SVM de destino para acesso aos dados se houver uma interrupção na SVM de origem. 1 o único SVM de fornecimento de dados abrange todo o sistema Cloud Volumes ONTAP. 


.2+| *Ficheiros* | Tamanho máximo | 16 TB 


| Máximo por volume | Depende do tamanho do volume, até 2 bilhões 


| *Volumes FlexClone* | Profundidade do clone hierárquico 2 | 499 


.3+| *Volumes FlexVol* | Máximo por nó | 500 


| Tamanho mínimo | 20 MB 


| Tamanho máximo | 100 TB 


| *Qtrees* | Máximo por FlexVol volume | 4.995 


| *Cópias Snapshot* | Máximo por FlexVol volume | 1.023 
|===
Notas:

. O Cloud Manager não oferece nenhuma configuração ou suporte de orquestração para a recuperação de desastres da SVM. Ele também não dá suporte a tarefas relacionadas a storage em uma SVM adicional. Use o System Manager ou a CLI para recuperação de desastres da SVM.
+
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856["Guia expresso de preparação para recuperação de desastres da SVM"^]
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857["Guia do SVM Disaster Recovery Express"^]


. Profundidade de clone hierárquica é a profundidade máxima de uma hierarquia aninhada de volumes FlexClone que pode ser criada a partir de um único FlexVol volume.




== Limites de armazenamento iSCSI

[cols="3*"]
|===
| Armazenamento iSCSI | Parâmetro | Limite 


.4+| *LUNs* | Máximo por nó | 1.024 


| Número máximo de mapas LUN | 1.024 


| Tamanho máximo | 16 TB 


| Máximo por volume | 512 


| *grupos* | Máximo por nó | 256 


.2+| *Iniciadores* | Máximo por nó | 512 


| Máximo por grupo | 128 


| * Sessões iSCSI* | Máximo por nó | 1.024 


.2+| *LIFs* | Máximo por porta | 1 


| Máximo por portset | 32 


| *Portsets* | Máximo por nó | 256 
|===